In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3664, 7427, 5276, 5270],
 [3664, 7427, 5276, 2183],
 [3664, 7254, 5276, 110],
 [7888, 7449, 5611, 3061, 5001],
 [7888, 7449, 5611, 3061, 9936],
 [171, 3664, 3328, 5276, 3100],
 [6538, 2834, 3798, 3061]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3664 7427 5276 5270]
 [   0    0    0    0 3664 7427 5276 2183]
 [   0    0    0    0 3664 7254 5276  110]
 [   0    0    0 7888 7449 5611 3061 5001]
 [   0    0    0 7888 7449 5611 3061 9936]
 [   0    0    0  171 3664 3328 5276 3100]
 [   0    0    0    0 6538 2834 3798 3061]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/Users/abhyudayatak/Downloads/simple_rnn_imdb-3/myenv/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step


array([[[ 0.01109039,  0.04026068,  0.01544895, -0.0387525 ,
         -0.04470887, -0.01789601, -0.02103759,  0.01741361,
          0.01177099, -0.00643501],
        [ 0.01109039,  0.04026068,  0.01544895, -0.0387525 ,
         -0.04470887, -0.01789601, -0.02103759,  0.01741361,
          0.01177099, -0.00643501],
        [ 0.01109039,  0.04026068,  0.01544895, -0.0387525 ,
         -0.04470887, -0.01789601, -0.02103759,  0.01741361,
          0.01177099, -0.00643501],
        [ 0.01109039,  0.04026068,  0.01544895, -0.0387525 ,
         -0.04470887, -0.01789601, -0.02103759,  0.01741361,
          0.01177099, -0.00643501],
        [ 0.01394681, -0.00542139,  0.00502864,  0.01395278,
         -0.04650119, -0.02500765,  0.00859385, -0.00300766,
         -0.04064979,  0.01165821],
        [-0.0382418 ,  0.03416571,  0.0338596 , -0.03258903,
          0.02671288, -0.03750478,  0.03039349,  0.01692211,
          0.01580742, -0.0309975 ],
        [ 0.01156399, -0.04006378,  0.04447258,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 3664, 7427, 5276, 5270], dtype=int32)

In [16]:
model.predict(embedded_docs[0].reshape(1, -1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step


array([[[ 0.01109039,  0.04026068,  0.01544895, -0.0387525 ,
         -0.04470887, -0.01789601, -0.02103759,  0.01741361,
          0.01177099, -0.00643501],
        [ 0.01109039,  0.04026068,  0.01544895, -0.0387525 ,
         -0.04470887, -0.01789601, -0.02103759,  0.01741361,
          0.01177099, -0.00643501],
        [ 0.01109039,  0.04026068,  0.01544895, -0.0387525 ,
         -0.04470887, -0.01789601, -0.02103759,  0.01741361,
          0.01177099, -0.00643501],
        [ 0.01109039,  0.04026068,  0.01544895, -0.0387525 ,
         -0.04470887, -0.01789601, -0.02103759,  0.01741361,
          0.01177099, -0.00643501],
        [ 0.01394681, -0.00542139,  0.00502864,  0.01395278,
         -0.04650119, -0.02500765,  0.00859385, -0.00300766,
         -0.04064979,  0.01165821],
        [-0.0382418 ,  0.03416571,  0.0338596 , -0.03258903,
          0.02671288, -0.03750478,  0.03039349,  0.01692211,
          0.01580742, -0.0309975 ],
        [ 0.01156399, -0.04006378,  0.04447258,  0.0